services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/django_proxy.conf:/etc/nginx/conf.d/django_proxy.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/auth:/etc/nginx/auth
      - ${PDFS_HOST_PATH}:/var/www/documentosCar:ro
    env_file:
      - ./.env
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
